id: P007986
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W22327
  title: ལྷ་མོའི་ཤོ་མོ།
  author: ''
  volumes:
    c16ff8665e68485f85f7c2ce5037e243:
      image_group_id: I1PD36257
      title: Volume 1 of lha mo'i sho mo
      volume_number: 1
      total_pages: 140
      base_file: v001.txt
