id: P007986
initial_creation_type: ocr
source_metadata:
  id: bdr:W22327
  title: ལྷ་མོའི་ཤོ་མོ།
  author: ''
  volumes:
    b5ef01228746496a94c21f704a958f6f:
      image_group_id: I1PD36257
      title: ''
      volume_number: 1
      total_pages: 140
ebook_metadata:
  title: ལྷ་མོའི་ཤོ་མོ།
  author: ''
  sku: P007986
  cover: cover.jpg
  layers:
  - pagination
