id: I30917862
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T10:51:35+00:00'
last_modified: '2022-06-09T08:20:02.308487+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22327
  title: ལྷ་མོའི་ཤོ་མོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '0301':
      image_group_id: I1PD36257
      title: Volume 1 of lha mo'i sho mo
      total_pages: 140
      order: 1
      base_file: 0301.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
